micronaut.application.name=minor-branch-creator
githuborg.repos[0]=micronaut-elasticsearch'
githuborg.repos[1]=micronaut-jmx'
githuborg.repos[2]=micronaut-micrometer'
githuborg.repos[3]='micronaut-opensearch'
githuborg.repos[4]='micronaut-graphql'
githuborg.repos[5]='micronaut-grpc'
githuborg.repos[6]='micronaut-guice'
githuborg.repos[7]='micronaut-jackson-xml'
githuborg.repos[8]='micronaut-jaxrs'
githuborg.repos[9]='micronaut-json-schema'
githuborg.repos[10]='micronaut-openapi'
githuborg.repos[11]='micronaut-serialization'
githuborg.repos[12]='micronaut-servlet'
githuborg.repos[13]='micronaut-spring'
githuborg.repos[14]='micronaut-aot'
githuborg.repos[15]='micronaut-sourcegen'
githuborg.repos[16]='micronaut-openrewrite'
githuborg.repos[17]='micronaut-aws'
githuborg.repos[18]='micronaut-azure'
githuborg.repos[19]='micronaut-object-storage'
githuborg.repos[20]='micronaut-discovery-client'
githuborg.repos[21]='micronaut-gcp'
githuborg.repos[22]='micronaut-kubernetes'
githuborg.repos[23]='micronaut-oracle-cloud'
githuborg.repos[24]='micronaut-pulsar'
githuborg.repos[25]='micronaut-tracing'
githuborg.repos[26]='micronaut-toml'
githuborg.repos[27]='micronaut-logging'
githuborg.repos[28]='micronaut-data'
githuborg.repos[29]='micronaut-cassandra'
githuborg.repos[30]='micronaut-coherence'
githuborg.repos[31]='micronaut-eclipsestore'
githuborg.repos[32]='micronaut-mongodb'
githuborg.repos[33]='micronaut-neo4j'
githuborg.repos[34]='micronaut-r2dbc'
githuborg.repos[35]='micronaut-redis'
githuborg.repos[36]='micronaut-sql'
githuborg.repos[37]='micronaut-problem-json'
githuborg.repos[38]='micronaut-groovy'
githuborg.repos[39]='micronaut-kotlin'
githuborg.repos[40]='micronaut-graal-languages'
githuborg.repos[41]='micronaut-jms'
githuborg.repos[42]='micronaut-kafka'
githuborg.repos[43]='micronaut-mqtt'
githuborg.repos[44]='micronaut-nats'
githuborg.repos[45]='micronaut-pulsar'
githuborg.repos[46]='micronaut-rabbitmq'
githuborg.repos[47]='micronaut-acme'
githuborg.repos[48]='micronaut-cache'
githuborg.repos[49]='micronaut-chatbots'
githuborg.repos[50]='micronaut-crac'
githuborg.repos[51]='micronaut-email'
githuborg.repos[52]='micronaut-picocli'
githuborg.repos[53]='micronaut-security'
githuborg.repos[54]='micronaut-session'
githuborg.repos[55]='micronaut-reactor'
githuborg.repos[56]='micronaut-rxjava3'
githuborg.repos[57]='micronaut-multitenancy'
githuborg.repos[58]='micronaut-rss'
githuborg.repos[59]='micronaut-views'
githuborg.repos[60]='micronaut-flyway'
githuborg.repos[61]='micronaut-liquibase'
githuborg.repos[62]='micronaut-test'
githuborg.repos[63]='micronaut-test-resources'
githuborg.repos[64]='micronaut-control-panel'
githuborg.repos[65]='micronaut-data'
githuborg.repos[66]='micronaut-security'
githuborg.repos[67]='micronaut-graphql'
githuborg.repos[68]='micronaut-spring'
githuborg.repos[69]='micronaut-kafka'
githuborg.repos[70]='micronaut-openapi'
githuborg.repos[71]='micronaut-langchain4j'
githuborg.repos[72]='micronaut-mcp'
githuborg.repos[73]='micronaut-validation'
githuborg.repos[74]='micronaut-hibernate-validator'
