[versions]
geb = "7.0"
selenium = "4.20.0"

[libraries]
logback-classic = { module = "ch.qos.logback:logback-classic" }

micronaut-runtime-groovy = { module = "io.micronaut.groovy:micronaut-runtime-groovy" }
micronaut-picocli = { module = "io.micronaut.picocli:micronaut-picocli" }
micronaut-serde-jackson = { module = "io.micronaut.serde:micronaut-serde-jackson" }
micronaut-serde-processor = { module = "io.micronaut.serde:micronaut-serde-processor" }

picocli = { module = "info.picocli:picocli" }
picocli-codegen = { module = "info.picocli:picocli-codegen" }

geb-core = { module = "org.gebish:geb-core", version.ref = "geb" }
selenium-firefox-driver = { module = "org.seleniumhq.selenium:selenium-firefox-driver", version.ref = "selenium" }
selenium-support = { module = "org.seleniumhq.selenium:selenium-support", version.ref = "selenium" }